name: CI

on:
  push:
    branches:
      - main
      - robo5000
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup cache for Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/cache
            node_modules
          key: node-cache-Linux-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-cache-Linux-yarn-

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 5. Build the application
      - name: Build the app
        run: yarn build

      - name: Lint project
        run: yarn lint